version: '3'
services:
  kafka:
    image: spotify/kafka
    container_name: kafka
  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.3.1
    container_name: kafka_rest
    ports:
      - 8082:8082
    links:
     - kafka
    environment:
      - KAFKA_REST_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_REST_HOST_NAME=kafka_rest
    depends_on:
      - kafka